name: deploy

on:
  workflow_dispatch:
  schedule:
    - cron: "0 8 * * 1"

jobs:
  deploy:
    strategy:
      matrix:
        language: ["python", "go", "node", "base"]
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4
        - run: |
            for variant in $(jq -r '.variants[]' source/${{ matrix.language }}/manifest.json); do
                jq \
                -s \
                'def rmerge(a; b): if (a|type)=="object" and (b|type)=="object" then reduce (b|keys[]) as $k (a; .[$k] = rmerge(.[$k]; b[$k])) elif (a|type)=="array" and (b|type)=="array" then a + b else b end; reduce .[] as $item ({}; rmerge(.; $item))' \
                source/${{ matrix.language }}/.devcontainer.json source/.devcontainer.json <(echo '{"build":{"args":{"VARIANT": "'"$variant"'" }}}') > source/${{ matrix.language }}/.devcontainer.$variant.json;
            done
        - uses: docker/setup-buildx-action@v3
        - uses: docker/login-action@v3
          with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GH_TOKEN }}
        - run: npm install -g @devcontainers/cli
        - run: |
            for variant in $(jq -r '.variants[]' source/${{ matrix.language }}/manifest.json); do
              devcontainer build \
                  --workspace-folder source/${{ matrix.language }} \
                  --config source/${{ matrix.language }}/.devcontainer.$variant.json \
                  --image-name ghcr.io/${{ github.actor }}/devcontainers/${{ matrix.language }}:$variant \
                  --cache-from ghcr.io/${{ github.actor }}/devcontainers/${{ matrix.language }}:$variant \
                  --push true
            done