name: deploy

on:
  workflow_dispatch:
  schedule:
    - cron: "0 8 * * 1"

jobs:
  deploy:
    strategy:
      matrix:
        language: ["python", "go", "node"]
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4
        - run: |
            for variant in $(jq -r '.variants[]' source/${{ matrix.language }}/manifest.json); do
              jq \
              --slurp \
              --sort-keys \
              '.[0] * .[1] * { build: { args: { VARIANT: "'"$variant"'" } } }' \
              source/.devcontainer.json source/${{ matrix.language }}/.devcontainer.json > source/${{ matrix.language }}/.devcontainer.$variant.json;
            done
        - uses: docker/setup-buildx-action@v3
        - uses: docker/login-action@v3
          with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GH_TOKEN }}
        - run: npm install -g @devcontainers/cli
        - run: |
            for variant in $(jq -r '.variants[]' source/${{ matrix.language }}/manifest.json); do
              devcontainer build \
                  --workspace-folder source/${{ matrix.language }} \
                  --config source/${{ matrix.language }}/.devcontainer.$variant.json \
                  --image-name ghcr.io/${{ github.actor }}/devcontainers/${{ matrix.language }}:$variant \
                  --cache-from ghcr.io/${{ github.actor }}/devcontainers/${{ matrix.language }}:$variant \
                  --push true
            done