name: CI/CD

on: 
  push:
    branches:
        - main

jobs:
  deploy:
    strategy:
      matrix:
        language: ["python"]
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v4
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3
        - name: Login to Docker Hub
          uses: docker/login-action@v3
          with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GH_TOKEN }}
        - name: Install devcontainer CLI
          run: npm install -g @devcontainers/cli
        - name: Build and push noble
          run: |
            devcontainer build \
                --workspace-folder src/ubuntu \
                --image-name ghcr.io/${{ github.actor }}/devcontainers/ubuntu \
                --cache-from ghcr.io/${{ github.actor }}/devcontainers/ubuntu \
                --push true
        - name: Build and push devcontainers/ubuntu
          run: |
            devcontainer build \
                --workspace-folder src/ubuntu \
                --image-name ghcr.io/${{ github.actor }}/devcontainers/ubuntu \
                --cache-from ghcr.io/${{ github.actor }}/devcontainers/ubuntu \
                --push true
        - name: Build and push devcontainers/{{ matrix.language }}
          run: |
            devcontainer build \
                --workspace-folder src/${{ matrix.language }} \
                --image-name ghcr.io/${{ github.actor }}/devcontainers/${{ matrix.language }} \
                --cache-from ghcr.io/${{ github.actor }}/devcontainers/${{ matrix.language }} \
                --push true